### ISSUE TITLE
Can't access papers view with super user

### ISSUE THREAD

**Issue by flaviobarros** [sujitpal/sherpa#1]
Thank you very much for sharing this project! But I could run it locally, but I am unable to access the paper's view. I can create a paper but even with superuser, I can't list all papers submitted. How can I get it to work?

**Comment by sujitpal** [comment]
You have to set your user (not the admin user) to have organizer rights (Attendee.is_organizer = True). You can do this from the admin console. Once you do that you should be able to log in as that user and point to /papers/ to see the list of papers. Idea is that submitters and attendees should not be able to see what the submissions are until they have been reviewed and accepted, but organizers can.
